# frozen_string_literal: true

require "json"
require "minitest/autorun"
require "open3"
require "rbconfig"
require "socket"
require "tmpdir"
require "zlib"

# Coverage for scripts/echis_seed.rb's dev-server-aligned data model
# (docs/echis-data-model.md). Most cases run in --metadata-only mode; the
# shape and reference-closure cases capture the real transaction bundles
# with a local stub server, the same pattern test/synthea_loader_http_test.rb
# establishes, since --metadata-only never serializes resource bodies.
class EchisSeedTest < Minitest::Test
  ROOT_DIR = File.expand_path("..", __dir__)
  GENERATOR = File.join(ROOT_DIR, "scripts", "echis_seed.rb")
  CONTENT = File.join(ROOT_DIR, "benchmarks", "echis", "content", "echis-content.json")
  TAG_SYSTEM = "https://www.example.com/CodeSystem/supervision-location"
  ACCEPT_TIMEOUT_SECONDS = 5
  HOUSEHOLD_OWNED_TYPES = %w[Group Patient RelatedPerson QuestionnaireResponse Encounter Observation DetectedIssue Task Condition].freeze

  def test_resource_counts_at_small_scale
    counts = run_seed(households: 100, run_id: "echis-seed-test-small").dig("echis", "resource_counts")

    assert_equal 100, counts["Group"]
    assert_equal 300, counts["Patient"]
    assert_equal 200, counts["RelatedPerson"], "one RelatedPerson per non-head household member"
    # One CHV catchment and one Community Health Unit: CHV + CHA staff.
    assert_equal 2, counts["Practitioner"]
    assert_equal 2, counts["PractitionerRole"]
    assert_equal 1, counts["CareTeam"]
    assert_equal 1, counts["Organization"]
    # 48 snapshot Locations (country + 47 counties) + unit, facility, ward, sub-county.
    assert_equal 52, counts["Location"]
    assert_equal 21, counts["Questionnaire"]
    assert_equal 34, counts["PlanDefinition"]
    assert_equal 7, counts["ActivityDefinition"]
    assert_operator counts["QuestionnaireResponse"], :>=, 100, "every household has a registration response"
    assert_operator counts["Observation"], :>=, 300, "every household has three WASH observations"
    %w[Encounter DetectedIssue Task Condition].each { |type| assert_operator counts[type].to_i, :>, 0, "expected some #{type}" }
    refute counts.key?("Specimen"), "Specimen must not appear unless --include-specimen is set"
  end

  def test_household_sizes_vary_around_the_average
    metadata = run_seed(households: 5, run_id: "echis-seed-test-sizes")
    # Sizes cycle 3, 4, 2, 3, 4 -> 16 individuals.
    assert_equal 16, metadata.dig("echis", "patients")
    assert_equal 16, metadata.dig("echis", "resource_counts", "Patient")
  end

  def test_shard_rerun_is_reproducible
    first = run_seed(households: 1000, shard_index: 1, shard_count: 4, run_id: "echis-seed-test-shard-a")
    second = run_seed(households: 1000, shard_index: 1, shard_count: 4, run_id: "echis-seed-test-shard-b")

    assert_equal first.dig("echis", "resource_counts"), second.dig("echis", "resource_counts")
  end

  def test_shards_partition_household_owned_resources_and_count_content_once
    single = run_seed(households: 1000, run_id: "echis-seed-test-single").dig("echis", "resource_counts")
    sharded = Array.new(4) { |index| run_seed(households: 1000, shard_index: index, shard_count: 4, run_id: "echis-seed-test-part-#{index}") }
      .map { |metadata| metadata.dig("echis", "resource_counts") }

    HOUSEHOLD_OWNED_TYPES.each do |type|
      assert_equal single[type], sharded.sum { |counts| counts[type].to_i }, "#{type} must be generated by exactly one shard"
    end
    assert_equal 21, sharded.sum { |counts| counts["Questionnaire"].to_i }, "reference content is counted by shard 0 only"
  end

  def test_seed_changes_the_generated_mix
    first = run_seed(households: 1000, seed: 1, run_id: "echis-seed-test-seed-1").dig("echis", "resource_counts")
    second = run_seed(households: 1000, seed: 2, run_id: "echis-seed-test-seed-2").dig("echis", "resource_counts")

    assert_equal first["Patient"], second["Patient"]
    refute_equal first["Observation"], second["Observation"]
  end

  def test_specimen_only_when_enabled
    counts = run_seed(households: 300, run_id: "echis-seed-test-specimen", include_specimen: true).dig("echis", "resource_counts")

    assert_operator counts["Specimen"].to_i, :>, 0
  end

  def test_gzipped_content_snapshot_is_accepted
    Dir.mktmpdir do |dir|
      gz = File.join(dir, "echis-content.json.gz")
      Zlib::GzipWriter.open(gz) { |writer| writer.write(File.read(CONTENT)) }

      plain = run_seed(households: 50, run_id: "echis-seed-test-plain").dig("echis", "resource_counts")
      zipped = run_seed(households: 50, run_id: "echis-seed-test-gz", content: gz).dig("echis", "resource_counts")
      assert_equal plain, zipped
    end
  end

  def test_missing_content_snapshot_fails_clearly
    Dir.mktmpdir do |dir|
      _stdout, stderr, status = Open3.capture3(
        RbConfig.ruby, GENERATOR, "--households", "1", "--seed", "1", "--run-id", "missing",
        "--metadata", File.join(dir, "m.json"), "--metadata-only", "--content", File.join(dir, "nope.json")
      )
      refute status.success?
      assert_match(/content snapshot not found/, stderr)
    end
  end

  def test_generated_resources_match_dev_server_shapes
    requests = capture_bundles(households: 100)
    content, households = requests
    resources = households["entry"].map { |entry| entry["resource"] }

    assert_equal 110, content["entry"].length, "reference content is loaded before household data"
    assert(households["entry"].all? { |entry| entry.dig("request", "method") == "PUT" })

    by_type = resources.group_by { |resource| resource["resourceType"] }
    %w[Group Patient RelatedPerson QuestionnaireResponse Encounter Observation Task DetectedIssue CareTeam].each do |type|
      by_type.fetch(type).each do |resource|
        tag = Array(resource.dig("meta", "tag")).find { |t| t["system"] == TAG_SYSTEM }
        assert_equal "echis-loc-chu000000", tag&.fetch("code", nil), "#{type}/#{resource["id"]} needs the supervision-location sync tag"
      end
    end

    group = by_type["Group"].first
    assert_equal "person", group["type"]
    assert_equal true, group["actual"]
    assert_equal "PractitionerRole/echis-chw000000", group.dig("managingEntity", "reference")
    assert_match(/ Household\z/, group["name"])

    patient = by_type["Patient"].first
    assert_equal "PractitionerRole/echis-chw000000", patient.dig("generalPractitioner", 0, "reference")
    assert_equal "KE", patient.dig("address", 0, "country")

    chv = by_type["PractitionerRole"].find { |role| role["id"] == "echis-chw000000" }
    assert_equal({ "system" => "https://nphiis.health.go.ke/fhir/CodeSystem/nphiis-roles", "code" => "CHV", "display" => "CHV" }, chv.dig("code", 0, "coding", 0))

    assert(by_type["Encounter"].all? { |encounter| encounter.dig("class", "code") == "FLD" })
    assert(by_type["QuestionnaireResponse"].all? { |response| response["questionnaire"].start_with?("https://echisv3.intellisoftkenya.com/fhir/Questionnaire/") })

    registration = by_type["QuestionnaireResponse"].find { |response| response["questionnaire"].end_with?("/household-registration") }
    assert_equal "Group/#{group["id"]}", registration.dig("subject", "reference")

    extracted = by_type["Observation"].select { |observation| observation["derivedFrom"] }
    response_ids = by_type["QuestionnaireResponse"].map { |response| "QuestionnaireResponse/#{response["id"]}" }
    assert(extracted.all? { |observation| response_ids.include?(observation.dig("derivedFrom", 0, "reference")) })
    assert(by_type["Observation"].any? { |observation| observation.dig("code", "coding", 0, "system") == "https://echisv3.intellisoftkenya.com/fhir/CodeSystem/under-5-observation" })
  end

  def test_every_reference_resolves_within_the_load
    content, households = capture_bundles(households: 100)
    loaded = (content["entry"] + households["entry"]).to_set { |entry| "#{entry.dig("resource", "resourceType")}/#{entry.dig("resource", "id")}" }

    dangling = households["entry"].flat_map { |entry| references(entry["resource"]) }.reject { |ref| loaded.include?(ref) }.uniq
    assert_empty dangling, "HAPI enforces referential integrity on write; these references would be rejected"
  end

  def test_household_bundles_are_byte_identical_across_runs
    assert_equal capture_bundles(households: 20), capture_bundles(households: 20)
  end

  # Regression: when a bundle holds the first households of two Community
  # Health Units, both units' Location chains were emitted into it, repeating
  # the facility/ward/sub-county they share -- HAPI rejects that transaction
  # (HAPI-0535), and the lost CHV then failed every later bundle (HAPI-1094).
  # That is what failed the hapi-lab-t3-devmodel T3 seed: shard 3 of 10 began
  # at household 99,999, so its first bundle spanned units 99 and 100. Here
  # shard 1 of 2 over 3,960 households begins at 1,980, so its first bundle
  # spans units 1 and 2, which share ward 0 and sub-county 0.
  def test_bundles_spanning_units_never_repeat_a_resource
    content, *households = capture_bundles(households: 3960, shard_index: 1, shard_count: 2)

    households.each_with_index do |bundle, position|
      keys = bundle["entry"].map { |entry| "#{entry.dig("resource", "resourceType")}/#{entry.dig("resource", "id")}" }
      duplicates = keys.tally.select { |_, count| count > 1 }.keys
      assert_empty duplicates, "household bundle #{position} repeats resources, which HAPI rejects as a transaction"
    end

    sent = content["entry"].to_set { |entry| "#{entry.dig("resource", "resourceType")}/#{entry.dig("resource", "id")}" }
    households.each_with_index do |bundle, position|
      bundle["entry"].each { |entry| sent << "#{entry.dig("resource", "resourceType")}/#{entry.dig("resource", "id")}" }
      dangling = bundle["entry"].flat_map { |entry| references(entry["resource"]) }.reject { |ref| sent.include?(ref) }.uniq
      assert_empty dangling, "household bundle #{position} references resources no earlier bundle created"
    end
  end

  def test_rejected_bundle_resends_its_shared_resources
    _content, rejected, following = capture_bundles(households: 200, reject_requests: [1], expect_success: false)

    %w[Organization/echis-org000001 Location/echis-loc-chu000000 PractitionerRole/echis-cha000000].each do |key|
      assert_includes resource_keys(rejected), key
      assert_includes resource_keys(following), key, "#{key} must be re-sent after the bundle carrying it was rejected"
    end
  end

  private

  def resource_keys(bundle)
    bundle["entry"].map { |entry| "#{entry.dig("resource", "resourceType")}/#{entry.dig("resource", "id")}" }
  end

  def run_seed(households:, run_id:, seed: 12345, shard_index: 0, shard_count: 1, include_specimen: false, content: nil)
    Dir.mktmpdir do |dir|
      metadata_path = File.join(dir, "metadata.json")
      args = [
        RbConfig.ruby, GENERATOR,
        "--households", households.to_s,
        "--seed", seed.to_s,
        "--run-id", run_id,
        "--metadata", metadata_path,
        "--metadata-only",
        "--shard-index", shard_index.to_s,
        "--shard-count", shard_count.to_s
      ]
      args << "--include-specimen" if include_specimen
      args.push("--content", content) if content

      stdout, stderr, status = Open3.capture3(*args)
      assert status.success?, "#{stdout}\n#{stderr}"

      JSON.parse(File.read(metadata_path))
    end
  end

  # Runs a live (non-metadata-only) seed against a stub server and returns
  # every transaction bundle it POSTed, in order. reject_requests lists the
  # 0-based request positions the stub answers with HTTP 400.
  def capture_bundles(households:, shard_index: 0, shard_count: 1, reject_requests: [], expect_success: true)
    server = TCPServer.new("127.0.0.1", 0)
    port = server.addr[1]
    thread = Thread.new { serve_transactions(server, reject_requests) }

    Dir.mktmpdir do |dir|
      stdout, stderr, status = Open3.capture3(
        RbConfig.ruby, GENERATOR,
        "--households", households.to_s,
        "--seed", "12345",
        "--run-id", "echis-seed-test-capture",
        "--metadata", File.join(dir, "metadata.json"),
        "--shard-index", shard_index.to_s,
        "--shard-count", shard_count.to_s,
        "--max-retries", "0",
        "--fhir-base-url", "http://127.0.0.1:#{port}/fhir"
      )
      assert_equal expect_success, status.success?, "#{stdout}\n#{stderr}"
    end

    server.close
    thread.join(ACCEPT_TIMEOUT_SECONDS)
    thread.value
  end

  def serve_transactions(server, reject_requests = [])
    requests = []
    loop do
      ready = IO.select([server], nil, nil, ACCEPT_TIMEOUT_SECONDS)
      break unless ready

      socket = server.accept
      headers = []
      while (line = socket.gets)
        break if line == "\r\n"

        headers << line
      end
      length = headers.find { |header| header.downcase.start_with?("content-length:") }.to_s.split(":", 2).last.to_i
      request = JSON.parse(socket.read(length))
      requests << request

      if reject_requests.include?(requests.length - 1)
        body = JSON.generate("resourceType" => "OperationOutcome", "issue" => [{ "severity" => "error", "code" => "processing", "diagnostics" => "rejected by test" }])
        socket.write "HTTP/1.1 400 Bad Request\r\nContent-Type: application/fhir+json\r\nContent-Length: #{body.bytesize}\r\nConnection: close\r\n\r\n#{body}"
        socket.close
        next
      end

      body = JSON.generate(
        "resourceType" => "Bundle",
        "type" => "transaction-response",
        "entry" => Array.new(request["entry"].length) { { "response" => { "status" => "201 Created" } } }
      )
      socket.write "HTTP/1.1 200 OK\r\nContent-Type: application/fhir+json\r\nContent-Length: #{body.bytesize}\r\nConnection: close\r\n\r\n#{body}"
      socket.close
    end
    requests
  rescue IOError, Errno::EBADF
    requests
  end

  def references(value)
    case value
    when Hash
      own = value["reference"].is_a?(String) && value["reference"].match?(%r{\A[A-Z][A-Za-z]+/[^/]+\z}) ? [value["reference"]] : []
      own + value.values.flat_map { |child| references(child) }
    when Array then value.flat_map { |child| references(child) }
    else []
    end
  end
end
