#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates a deterministic, sharded eCHIS household/CHW dataset whose shape
# follows the eCHIS dev server (https://echisv3.intellisoftkenya.com/fhir):
# households are Groups of Patients managed by a CHV PractitionerRole inside
# a Kenya administrative Location hierarchy, every patient-data resource
# carries the dev server's supervision-location sync tag, and care happens
# through the server's own Questionnaires -- each visit is a
# QuestionnaireResponse generated by walking the real form (enableWhen
# honoured), with Observations extracted exactly where the form marks items
# observation-extract, plus the DetectedIssue/Task/Condition records the
# decision-support PlanDefinitions imply. See docs/echis-data-model.md.
#
# The reference content (Questionnaires, PlanDefinitions, ActivityDefinitions,
# country/county Locations) is a snapshot taken by
# scripts/snapshot_echis_content.rb and is PUT before any household data.

require "date"
require "fileutils"
require "json"
require "net/http"
require "openssl"
require "optparse"
require "set"
require "time"
require "uri"
require "zlib"

# When stdout isn't a real terminal (piped through `scripts/lab`, captured
# by the Lab Control UI's child_process spawn into a log file/SSE stream --
# the normal case), Ruby fully buffers writes instead of line-buffering
# them. Progress output then sits invisible in the process's internal
# buffer for however long it takes to fill (observed live: tens of minutes
# of real progress with zero new log lines, confirmed lagging by ~12
# percentage points against the FHIR server's own resource count) rather
# than appearing as it happens. Forcing sync mode makes every `puts`/`print`
# flush immediately regardless of TTY-ness, which is what "live progress"
# actually requires.
$stdout.sync = true

class SeedError < StandardError; end

DEFAULT_CONTENT_PATH = File.expand_path("../benchmarks/echis/content/echis-content.json", __dir__)

options = {
  individuals_per_household: 3,
  batch_size: 100,
  timeout: 120,
  shard_index: 0,
  shard_count: 1,
  metadata_only: false,
  include_specimen: false,
  content: DEFAULT_CONTENT_PATH,
  max_retries: 3
}

OptionParser.new do |opts|
  opts.banner = "Usage: scripts/echis_seed.rb --households N --seed S --run-id RUN_ID --metadata FILE [--fhir-base-url URL | --metadata-only]"
  opts.on("--households N", Integer, "Total household count across all shards (not this shard's own slice) -- combined with --shard-index/--shard-count to compute this invocation's [start_index, end_index) range.") { |v| options[:households] = v }
  opts.on("--individuals-per-household N", Integer, "Average individuals per household; default 3. Household sizes cycle N, N+1, N-1 when N >= 2.") { |v| options[:individuals_per_household] = v }
  opts.on("--seed S", Integer, "Deterministic seed; drives demographics, visit mix, and form answers.") { |v| options[:seed] = v }
  opts.on("--run-id RUN_ID", "Run identifier.") { |v| options[:run_id] = v }
  opts.on("--metadata FILE", "Dataset metadata JSON file to write.") { |v| options[:metadata] = v }
  opts.on("--fhir-base-url URL", "FHIR base URL that accepts transaction bundle POSTs. Required unless --metadata-only.") { |v| options[:fhir_base_url] = v }
  opts.on("--content FILE", "Reference content snapshot (.json or .json.gz) from scripts/snapshot_echis_content.rb; default benchmarks/echis/content/echis-content.json.") { |v| options[:content] = v }
  opts.on("--batch-size N", Integer, "Households per transaction bundle; default 100.") { |v| options[:batch_size] = v }
  opts.on("--timeout SECONDS", Integer, "HTTP open/read timeout in seconds; default 120.") { |v| options[:timeout] = v }
  opts.on("--max-retries N", Integer, "Retries per transaction bundle on network errors or HTTP 409/412/429/5xx; default 3. Safe because every entry is an idempotent PUT.") { |v| options[:max_retries] = v }
  opts.on("--shard-index N", Integer, "This invocation's shard number (0-based); default 0.") { |v| options[:shard_index] = v }
  opts.on("--shard-count N", Integer, "Total number of shards; default 1.") { |v| options[:shard_count] = v }
  opts.on("--metadata-only", "Compute and record dataset metadata without making HTTP calls.") { options[:metadata_only] = true }
  opts.on("--include-specimen", "Emit a blood Specimen for every malaria rapid test taken during an under-5 assessment; off by default.") { options[:include_specimen] = true }
  opts.on("-h", "--help", "Show this help.") do
    puts opts
    exit
  end
end.parse!

# --- Systems and URLs, copied verbatim from the eCHIS dev server -------------

SUPERVISION_LOCATION_TAG_SYSTEM = "https://www.example.com/CodeSystem/supervision-location"
ADMINISTRATIVE_LEVEL_SYSTEM = "http://ohs.dev/codes/administrative-level"
PHYSICAL_TYPE_SYSTEM = "http://terminology.hl7.org/CodeSystem/location-physical-type"
LOCATION_IDENTIFIER_SYSTEM = "urn:demo:location"
HOUSEHOLD_IDENTIFIER_SYSTEM = "urn:demo:household"
PATIENT_IDENTIFIER_SYSTEM = "urn:demo:patient"
PRACTITIONER_IDENTIFIER_SYSTEM = "http://hl7.org/fhir/administrative-identifier"
PRACTITIONER_LOCATION_EXTENSION = "http://example.org/location"
PRACTITIONER_ROLE_GROUP_EXTENSION = "http://example.org/fhir/StructureDefinition/role-group"
NPHIIS_ROLE_SYSTEM = "https://nphiis.health.go.ke/fhir/CodeSystem/nphiis-roles"
ROLE_CODE_SYSTEM = "http://terminology.hl7.org/CodeSystem/v3-RoleCode"
ACT_CODE_SYSTEM = "http://terminology.hl7.org/CodeSystem/v3-ActCode"
INSTANTIATES_PLAN_DEFINITION_EXTENSION = "http://icl.ohs.echis.reference/fhir/StructureDefinition/instantiates-plan-definition"
OBSERVATION_EXTRACT_EXTENSION = "http://icl.ohs.echis.reference/fhir/StructureDefinition/observation-extract"
LAST_LAUNCHED_EXTENSION = "http://github.com/google-android/questionnaire-lastLaunched-timestamp"
DECISION_SUPPORT_RULE_SYSTEM = "http://icl.ohs.echis.reference/fhir/CodeSystem/decision-support-rule"
HOUSEHOLD_WASH_SYSTEM = "https://echisv3.intellisoftkenya.com/fhir/CodeSystem/household-wash"
COUNTY_IDENTIFIER_SYSTEM = "urn:echis:ke:county"
SNOMED_SYSTEM = "http://snomed.info/sct"

# Every date in the dataset is relative to this fixed day, never the clock,
# so a re-run of any shard reproduces byte-identical resources.
REFERENCE_DATE = Date.new(2026, 9, 1)

# --- Catchment hierarchy -------------------------------------------------------
#
# Sized to Kenya's community health strategy: one CHV (Community Health
# Promoter) per 100 households, ten CHVs and one CHA per Community Health
# Unit (~1,000 households). At the 10M-household peak tier this yields 100k
# CHVs, 10k CHUs, 5k link facilities, ~1.7k wards and ~333 sub-counties --
# close to Kenya's real ~1,450 wards and ~300 sub-counties. Every index is
# pure integer division from the GLOBAL household index, so every shard
# computes identical hierarchy ids with no coordination. Sub-counties are
# spread round-robin across the snapshot's 47 real counties.
CHW_CATCHMENT_SIZE = 100
CHVS_PER_UNIT = 10
UNITS_PER_FACILITY = 2
FACILITIES_PER_WARD = 3
WARDS_PER_SUB_COUNTY = 5

def chw_index_for(household_index) = household_index / CHW_CATCHMENT_SIZE
def unit_index_for(chw_index) = chw_index / CHVS_PER_UNIT
def facility_index_for(unit_index) = unit_index / UNITS_PER_FACILITY
def ward_index_for(facility_index) = facility_index / FACILITIES_PER_WARD
def sub_county_index_for(ward_index) = ward_index / WARDS_PER_SUB_COUNTY

# Household sizes cycle N, N+1, N-1 around the requested average, so the
# roster varies like the dev server's (1-5 members) while individual indices
# stay contiguous and computable in O(1) from the household index alone.
HOUSEHOLD_SIZE_OFFSETS = [0, 1, -1].freeze

def household_size(household_index, individuals_per_household)
  return individuals_per_household if individuals_per_household < 2

  individuals_per_household + HOUSEHOLD_SIZE_OFFSETS[household_index % 3]
end

def first_individual_index(household_index, individuals_per_household)
  return household_index * individuals_per_household if individuals_per_household < 2

  (household_index * individuals_per_household) + (household_index % 3 == 2 ? 1 : 0)
end

def total_individuals(households, individuals_per_household)
  first_individual_index(households, individuals_per_household)
end

# --- Deterministic randomness --------------------------------------------------
#
# SplitMix64 keyed on (seed, stream, salt). Each person/household/visit gets
# its own stream, so a shard never depends on what another shard drew, and
# Zlib.crc32 (not String#hash, which Ruby randomizes per process) turns salts
# into stable integers.
MASK64 = (1 << 64) - 1

def mix64(value)
  value = (value + 0x9E3779B97F4A7C15) & MASK64
  value = ((value ^ (value >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
  value = ((value ^ (value >> 27)) * 0x94D049BB133111EB) & MASK64
  value ^ (value >> 31)
end

class Draw
  def initialize(seed, stream, salt)
    @state = mix64(mix64(seed & MASK64) ^ mix64((stream & MASK64) ^ Zlib.crc32(salt.to_s)))
  end

  def next_u64
    @state = (@state + 0x9E3779B97F4A7C15) & MASK64
    mix64(@state)
  end

  def float = (next_u64 >> 11).fdiv(1 << 53)
  def chance?(probability) = float < probability
  def int(min, max) = min + (next_u64 % (max - min + 1))
  def pick(values) = values[next_u64 % values.length]

  def weighted(pairs)
    total = pairs.sum { |_, weight| weight }
    target = float * total
    pairs.each do |value, weight|
      target -= weight
      return value if target < 0
    end
    pairs.last.first
  end
end

# --- Names ---------------------------------------------------------------------

FEMALE_GIVEN_NAMES = %w[
  Wanjiku Akinyi Chepkoech Achieng Njeri Atieno Wambui Nafula Moraa Kerubo Nyambura Jepkemoi
  Mumbua Zawadi Halima Amina Grace Faith Mercy Esther Joan Anita Lydia Naliaka Chemutai Asha
].freeze
MALE_GIVEN_NAMES = %w[
  Otieno Kiprotich Mwangi Kamau Ochieng Wafula Kipngeno Mutua Omondi Njoroge Barasa Kibet
  Hassan Juma Samuel Peter John Brian Kevin David Ethan Joseph Daniel Emmanuel Kiplagat Musa
].freeze
FAMILY_NAMES = %w[
  Langat Kipkorir Otieno Mwangi Kamau Wanjala Odhiambo Kiptoo Mutua Njoroge Barasa Chege
  Onyango Wekesa Kariuki Rotich Cheruiyot Owino Ndirangu Mohamed Ali Nyaga Muriuki Ouma
].freeze

def given_names(draw, gender)
  pool = gender == "female" ? FEMALE_GIVEN_NAMES : MALE_GIVEN_NAMES
  first = draw.pick(pool)
  second = draw.pick(pool)
  second = pool[(pool.index(second) + 1) % pool.length] if second == first
  [first, second]
end

def phone_number(draw) = format("07%08d", draw.int(0, 99_999_999))

# --- Reference content ---------------------------------------------------------

REQUIRED_QUESTIONNAIRES = %w[
  household-registration under-5-assessment-service-questionnaire immunization-service-questionnaire
  defaulter-follow-up-questionnaire pregnancy-screening-registration-questionnaire
  pregnancy-home-service-questionnaire mother-newborn-pnc-home-service-questionnaire
  diabetes-service-questionnaire tb-service-questionnaire referral-follow-up-questionnaire
  death-report-questionnaire
].freeze

class Content
  attr_reader :resources, :counties, :country

  def initialize(resources)
    @resources = resources
    @questionnaires = resources.select { |r| r["resourceType"] == "Questionnaire" }.to_h { |r| [r["id"], r] }
    @plan_definitions = resources.select { |r| r["resourceType"] == "PlanDefinition" }.to_h { |r| [r["id"], r] }
    locations = resources.select { |r| r["resourceType"] == "Location" }
    @country = locations.find { |location| Content.level(location) == "country" }
    @counties = locations.select { |location| Content.level(location) == "county" }.sort_by { |county| Content.county_code(county) }

    missing = REQUIRED_QUESTIONNAIRES.reject { |id| @questionnaires.key?(id) }
    raise SeedError, "content snapshot is missing Questionnaire(s): #{missing.join(", ")}" unless missing.empty?
    raise SeedError, "content snapshot has no county Locations" if @counties.empty?
  end

  def self.level(location)
    Array(location["type"]).flat_map { |type| Array(type["coding"]) }
      .find { |coding| coding["system"] == ADMINISTRATIVE_LEVEL_SYSTEM }&.fetch("code", nil)
  end

  def self.county_code(county)
    Array(county["identifier"]).find { |identifier| identifier["system"] == COUNTY_IDENTIFIER_SYSTEM }&.fetch("value", nil) || county["name"].to_s
  end

  def questionnaire(id) = @questionnaires.fetch(id)
  def plan_title(id) = @plan_definitions.dig(id, "title") || id
end

def load_content(path)
  raise SeedError, "content snapshot not found: #{path} (create it with scripts/snapshot_echis_content.rb)" unless File.file?(path)

  raw = path.end_with?(".gz") ? Zlib::GzipReader.open(path, &:read) : File.read(path)
  resources = Array(JSON.parse(raw)["entry"]).map { |entry| entry["resource"] }.compact
  raise SeedError, "content snapshot #{path} contains no resources" if resources.empty?

  Content.new(resources)
rescue JSON::ParserError, Zlib::Error => e
  raise SeedError, "content snapshot #{path} could not be read: #{e.message}"
end

# --- HTTP ----------------------------------------------------------------------

RETRYABLE_HTTP_CODES = [409, 412, 429, 500, 502, 503, 504].freeze

def status_success?(status)
  code = status.to_s.split(/\s+/, 2).first.to_i
  code >= 200 && code < 400
end

def post_bundle(uri, bundle, timeout)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = uri.scheme == "https"
  http.open_timeout = timeout
  http.read_timeout = timeout

  request = Net::HTTP::Post.new(uri.request_uri.empty? ? "/" : uri.request_uri)
  request["Accept"] = "application/fhir+json"
  request["Content-Type"] = "application/fhir+json"
  request.body = JSON.generate(bundle)

  http.request(request)
end

# Shards PUT the same reference content and boundary-straddling catchment
# resources concurrently, which HAPI can reject with a version conflict or a
# unique-constraint 500 when two creates race. Every entry is an idempotent
# PUT of identical content, so replaying the whole bundle is safe.
def post_bundle_with_retries(uri, bundle, timeout, max_retries)
  attempt = 0
  loop do
    begin
      response = post_bundle(uri, bundle, timeout)
      return response unless RETRYABLE_HTTP_CODES.include?(response.code.to_i) && attempt < max_retries
    rescue IOError, SystemCallError, Timeout::Error, OpenSSL::SSL::SSLError, Net::HTTPBadResponse
      raise if attempt >= max_retries
    end
    attempt += 1
    sleep([2**attempt, 30].min)
  end
end

def response_entries(response_body)
  parsed = JSON.parse(response_body)
  return [] unless parsed.is_a?(Hash) && parsed["resourceType"] == "Bundle"

  Array(parsed["entry"])
rescue JSON::ParserError
  []
end

def put_entry(resource)
  {
    "resource" => resource,
    "request" => { "method" => "PUT", "url" => "#{resource["resourceType"]}/#{resource["id"]}" }
  }
end

# --- Resource ids ----------------------------------------------------------------

def household_id(household_index) = format("echis-hh%08d", household_index)
def patient_id(individual_index) = format("echis-p%08d", individual_index)
def related_person_id(individual_index) = format("echis-rp%08d", individual_index)
def chw_practitioner_role_id(chw_index) = format("echis-chw%06d", chw_index)
def practitioner_id(chw_index) = format("echis-pr%06d", chw_index)
def care_team_id(chw_index) = format("echis-ct%06d", chw_index)
def cha_practitioner_role_id(unit_index) = format("echis-cha%06d", unit_index)
def cha_practitioner_id(unit_index) = format("echis-pr-cha%06d", unit_index)
def unit_location_id(unit_index) = format("echis-loc-chu%06d", unit_index)
def facility_location_id(facility_index) = format("echis-loc-fac%06d", facility_index)
def ward_location_id(ward_index) = format("echis-loc-ward%06d", ward_index)
def sub_county_location_id(sub_county_index) = format("echis-loc-sub%06d", sub_county_index)
def organization_id = "echis-org000001"
def visit_resource_id(kind, slug, individual_index, suffix = nil)
  base = format("echis-%s-%s%08d", kind, slug, individual_index)
  suffix.nil? ? base : format("%s-%02d", base, suffix)
end

# --- Small builders ------------------------------------------------------------

def reference(type, id, display = nil)
  ref = { "reference" => "#{type}/#{id}" }
  ref["display"] = display if display
  ref
end

def sync_tag(unit_id) = { "tag" => [{ "system" => SUPERVISION_LOCATION_TAG_SYSTEM, "code" => unit_id }] }
def plan_definition_extension(plan_definition_id) = { "url" => INSTANTIATES_PLAN_DEFINITION_EXTENSION, "valueCanonical" => "PlanDefinition/#{plan_definition_id}" }
def role_coding(code) = { "system" => NPHIIS_ROLE_SYSTEM, "code" => code, "display" => code }
def timestamp(time) = time.utc.strftime("%Y-%m-%dT%H:%M:%SZ")
def day_time(date, minutes_after_seven) = Time.utc(date.year, date.month, date.day, 7, 0, 0) + (minutes_after_seven * 60)
def full_name(person) = "#{person.given.join(" ")} #{person.family}"
def county_short_name(county) = county["name"].to_s.sub(/\s+County\z/, "")

# --- Catchment (Location hierarchy + staff) --------------------------------------

Catchment = Struct.new(
  :unit_index, :unit_id, :unit_name, :facility_id, :facility_name, :ward_id, :ward_name,
  :sub_county_id, :sub_county_name, :county, :cha_name, keyword_init: true
)

def catchment_for(unit_index, content, seed, cache)
  cache[unit_index] ||= begin
    facility_index = facility_index_for(unit_index)
    ward_index = ward_index_for(facility_index)
    sub_county_index = sub_county_index_for(ward_index)
    county = content.counties[sub_county_index % content.counties.length]
    cha_draw = Draw.new(seed, unit_index, "cha")
    cha_gender = cha_draw.chance?(0.6) ? "female" : "male"
    Catchment.new(
      unit_index: unit_index,
      unit_id: unit_location_id(unit_index),
      unit_name: format("Community Health Unit %d", unit_index + 1),
      facility_id: facility_location_id(facility_index),
      facility_name: format("%s Health Centre %d", county_short_name(county), facility_index + 1),
      ward_id: ward_location_id(ward_index),
      ward_name: format("Ward %d", ward_index + 1),
      sub_county_id: sub_county_location_id(sub_county_index),
      sub_county_name: format("%s Sub-County %d", county_short_name(county), sub_county_index + 1),
      county: county,
      cha_name: "#{given_names(cha_draw, cha_gender).first} #{cha_draw.pick(FAMILY_NAMES)}"
    )
  end
end

def location_resource(id:, name:, level:, level_display:, physical_code:, physical_display:, parent_id:, parent_name:)
  {
    "resourceType" => "Location",
    "id" => id,
    "identifier" => [{ "system" => LOCATION_IDENTIFIER_SYSTEM, "value" => id }],
    "status" => "active",
    "name" => name,
    "mode" => "instance",
    "type" => [{ "coding" => [{ "system" => ADMINISTRATIVE_LEVEL_SYSTEM, "code" => level, "display" => level_display }] }],
    "physicalType" => { "coding" => [{ "system" => PHYSICAL_TYPE_SYSTEM, "code" => physical_code, "display" => physical_display }] },
    "partOf" => reference("Location", parent_id, parent_name)
  }
end

def catchment_resources(catchment)
  county = catchment.county
  unit_tag = sync_tag(catchment.unit_id)
  [
    location_resource(id: catchment.sub_county_id, name: catchment.sub_county_name, level: "sub-county", level_display: "Sub-county",
                      physical_code: "jdn", physical_display: "Jurisdiction", parent_id: county["id"], parent_name: county["name"]),
    location_resource(id: catchment.ward_id, name: catchment.ward_name, level: "ward", level_display: "Ward",
                      physical_code: "jdn", physical_display: "Jurisdiction", parent_id: catchment.sub_county_id, parent_name: catchment.sub_county_name),
    location_resource(id: catchment.facility_id, name: catchment.facility_name, level: "facility", level_display: "Facility",
                      physical_code: "bu", physical_display: "Building", parent_id: catchment.ward_id, parent_name: catchment.ward_name),
    location_resource(id: catchment.unit_id, name: catchment.unit_name, level: "unit", level_display: "Community Health Unit",
                      physical_code: "area", physical_display: "Area", parent_id: catchment.facility_id, parent_name: catchment.facility_name),
    staff_practitioner(cha_practitioner_id(catchment.unit_index), catchment.cha_name, "CHA", catchment, Draw.new(0, catchment.unit_index, "cha-phone")),
    staff_role(cha_practitioner_role_id(catchment.unit_index), cha_practitioner_id(catchment.unit_index), catchment.cha_name, "CHA", catchment,
               REFERENCE_DATE - (400 + (catchment.unit_index % 900))).merge("meta" => unit_tag)
  ]
end

def staff_practitioner(id, name, role_group, catchment, draw)
  given, family = name.split(" ", 2)
  {
    "resourceType" => "Practitioner",
    "id" => id,
    "extension" => [
      { "url" => PRACTITIONER_LOCATION_EXTENSION, "valueReference" => reference("Location", catchment.unit_id, catchment.unit_name) },
      { "url" => PRACTITIONER_ROLE_GROUP_EXTENSION, "valueString" => role_group }
    ],
    "identifier" => [{ "system" => PRACTITIONER_IDENTIFIER_SYSTEM, "value" => id }],
    "active" => true,
    "name" => [{ "use" => "official", "family" => family, "given" => [given] }],
    "telecom" => [{ "system" => "phone", "value" => phone_number(draw), "use" => "mobile" }]
  }
end

def staff_role(id, practitioner_id, name, role_code, catchment, start_date)
  {
    "resourceType" => "PractitionerRole",
    "id" => id,
    "active" => true,
    "period" => { "start" => start_date.iso8601 },
    "practitioner" => reference("Practitioner", practitioner_id, name),
    "code" => [{ "coding" => [role_coding(role_code)] }],
    "location" => [reference("Location", catchment.unit_id, catchment.unit_name)]
  }
end

def chv_name(chw_index, seed)
  draw = Draw.new(seed, chw_index, "chv")
  gender = draw.chance?(0.7) ? "female" : "male"
  "#{given_names(draw, gender).first} #{draw.pick(FAMILY_NAMES)}"
end

def chw_resources(chw_index, catchment, seed)
  name = chv_name(chw_index, seed)
  role_id = chw_practitioner_role_id(chw_index)
  [
    staff_practitioner(practitioner_id(chw_index), name, "CHV", catchment, Draw.new(seed, chw_index, "chv-phone")),
    staff_role(role_id, practitioner_id(chw_index), name, "CHV", catchment, REFERENCE_DATE - (300 + (chw_index % 1200)))
      .merge("meta" => sync_tag(catchment.unit_id)),
    {
      "resourceType" => "CareTeam",
      "id" => care_team_id(chw_index),
      "meta" => sync_tag(catchment.unit_id),
      "status" => "active",
      "name" => "#{name} Care Team",
      "participant" => [
        { "role" => [{ "coding" => [role_coding("CHV")] }], "member" => reference("PractitionerRole", role_id, name) },
        { "role" => [{ "coding" => [role_coding("CHA")] }], "member" => reference("PractitionerRole", cha_practitioner_role_id(catchment.unit_index), catchment.cha_name) }
      ],
      "managingOrganization" => [reference("Organization", organization_id)]
    }
  ]
end

def organization_resource
  {
    "resourceType" => "Organization",
    "id" => organization_id,
    "active" => true,
    "name" => "eCHIS Benchmark Implementing Organization",
    "type" => [{
      "coding" => [{ "system" => "http://terminology.hl7.org/CodeSystem/organization-type", "code" => "prov", "display" => "Healthcare Provider" }]
    }]
  }
end

# --- Household roster ------------------------------------------------------------

Person = Struct.new(:index, :id, :role, :relationship, :gender, :age_days, :given, :family, :phone, keyword_init: true) do
  def birth_date = REFERENCE_DATE - age_days
  def age_years = age_days / 365
  def age_months = age_days / 30
end

RELATIONSHIP_DISPLAYS = { "SPS" => "Spouse", "CHILD" => "Child", "PRN" => "Parent" }.freeze
INVERSE_RELATIONSHIP = { "SPS" => "SPS", "CHILD" => "PRN", "PRN" => "CHILD" }.freeze
UNDER_FIVE_SHARE_OF_CHILDREN = 0.45

def household_roster(household_index, individuals_per_household, seed)
  draw = Draw.new(seed, household_index, "household")
  family = draw.pick(FAMILY_NAMES)
  head_gender = draw.chance?(0.35) ? "female" : "male"
  head_age = draw.int(22, 70)
  size = household_size(household_index, individuals_per_household)
  start = first_individual_index(household_index, individuals_per_household)

  Array.new(size) do |offset|
    index = start + offset
    person_draw = Draw.new(seed, index, "person")
    role, relationship, gender, age_days =
      if offset.zero?
        ["head", nil, head_gender, (head_age * 365) + person_draw.int(0, 364)]
      elsif offset == 1 && person_draw.chance?(0.8)
        spouse_age = (head_age + person_draw.int(-8, 3)).clamp(18, 80)
        ["spouse", "SPS", head_gender == "female" ? "male" : "female", (spouse_age * 365) + person_draw.int(0, 364)]
      elsif offset == size - 1 && size >= 4 && person_draw.chance?(0.12)
        ["parent", "PRN", person_draw.chance?(0.6) ? "female" : "male", (person_draw.int(60, 88) * 365) + person_draw.int(0, 364)]
      else
        max_child_days = [((head_age - 15) * 365) - 1, 0].max
        child_days =
          if person_draw.chance?(UNDER_FIVE_SHARE_OF_CHILDREN)
            person_draw.int(0, (5 * 365) - 1)
          else
            person_draw.int(5 * 365, (18 * 365) - 1)
          end
        ["child", "CHILD", person_draw.chance?(0.5) ? "female" : "male", [child_days, max_child_days].min]
      end
    Person.new(
      index: index, id: patient_id(index), role: role, relationship: relationship, gender: gender, age_days: age_days,
      given: given_names(person_draw, gender), family: family, phone: age_days >= 18 * 365 ? phone_number(person_draw) : nil
    )
  end
end

def patient_resource(person, head, catchment, household_index, chv, deceased_at)
  resource = {
    "resourceType" => "Patient",
    "id" => person.id,
    "meta" => sync_tag(catchment.unit_id),
    "identifier" => [{ "system" => PATIENT_IDENTIFIER_SYSTEM, "value" => person.id }],
    "active" => true,
    "name" => [{ "use" => "official", "family" => person.family, "given" => person.given }]
  }
  resource["telecom"] = [{ "system" => "phone", "value" => person.phone, "use" => "mobile" }] if person.phone
  resource["gender"] = person.gender
  resource["birthDate"] = person.birth_date.iso8601
  resource["deceasedDateTime"] = timestamp(deceased_at) if deceased_at
  resource["address"] = [household_address(catchment, household_index)]
  if person.relationship
    resource["contact"] = [{
      "relationship" => [{ "coding" => [{ "system" => ROLE_CODE_SYSTEM, "code" => person.relationship, "display" => RELATIONSHIP_DISPLAYS[person.relationship] }] }],
      "name" => { "family" => head.family, "given" => head.given }
    }]
  end
  resource["generalPractitioner"] = [reference("PractitionerRole", chv[:role_id], chv[:name])]
  resource
end

def village_name(household_index) = format("Village %d", (household_index / 250) + 1)

def household_address(catchment, household_index)
  {
    "use" => "home",
    "line" => ["#{village_name(household_index)}, #{catchment.ward_name}"],
    "city" => village_name(household_index),
    "district" => catchment.sub_county_name,
    "state" => county_short_name(catchment.county),
    "country" => "KE"
  }
end

def related_person_resource(person, head, catchment)
  code = INVERSE_RELATIONSHIP.fetch(person.relationship)
  resource = {
    "resourceType" => "RelatedPerson",
    "id" => related_person_id(person.index),
    "meta" => sync_tag(catchment.unit_id),
    "active" => true,
    "patient" => reference("Patient", person.id),
    "relationship" => [{ "coding" => [{ "system" => ROLE_CODE_SYSTEM, "code" => code, "display" => RELATIONSHIP_DISPLAYS[code] }] }],
    "name" => [{ "use" => "official", "family" => head.family, "given" => head.given }],
    "gender" => head.gender
  }
  resource["telecom"] = [{ "system" => "phone", "value" => head.phone, "use" => "mobile" }] if head.phone
  resource
end

def group_resource(household_index, roster, catchment, chv, registered_on)
  head = roster.first
  {
    "resourceType" => "Group",
    "id" => household_id(household_index),
    "meta" => sync_tag(catchment.unit_id),
    "identifier" => [{ "system" => HOUSEHOLD_IDENTIFIER_SYSTEM, "value" => household_id(household_index) }],
    "active" => true,
    "type" => "person",
    "actual" => true,
    "name" => "#{head.family} Household",
    "managingEntity" => reference("PractitionerRole", chv[:role_id], chv[:name]),
    "member" => roster.map do |person|
      { "entity" => reference("Patient", person.id, full_name(person)), "period" => { "start" => registered_on.iso8601 } }
    end
  }
end

# --- Questionnaire walking -------------------------------------------------------
#
# Answers are drawn from each item's own answerOption list, so a snapshot
# refresh that changes a form changes the generated responses with no code
# change. ANSWER_PROFILES only biases the draw toward realistic prevalence
# (danger signs rare, availability common); unprofiled yes/no questions
# default to DEFAULT_P_YES and multi-option questions that offer "none"
# pick it most of the time.
DEFAULT_P_YES = 0.2
NONE_OPTION_PROBABILITY = 0.85

ANSWER_PROFILES = {
  # Under 5 Assessment Service
  "is-child-name-sick" => { p_yes: 0.35 },
  "does-name-have-a-fever-hotness-of-the-body" => { p_yes: 0.45 },
  "how-many-days-has-the-fever-lasted" => { range: 1..5 },
  "do-you-have-a-thermometer" => { p_yes: 0.4 },
  "child-temperature-celsius" => { range: 35.2..39.4 },
  "has-name-taken-paracetamol-in-the-last-6-hrs" => { p_yes: 0.3 },
  "does-name-have-a-cough" => { p_yes: 0.4 },
  "has-name-taken-al-artemether-lumefantrine-in-the-last-one-week" => { p_yes: 0.1 },
  "rapid-malaria-tests-results" => { weights: { "positive" => 25, "negative" => 70, "invalid" => 5 } },
  "repeat-rapid-malaria-tests-results" => { weights: { "positive" => 25, "negative" => 70, "invalid" => 5 } },
  "is-there-chest-in-drawing" => { p_yes: 0.04 },
  "does-name-have-diarrhoea-3-or-more-loose-stools-in-24-hrs" => { p_yes: 0.25 },
  "how-many-days-has-the-diarrhoea-lasted" => { range: 1..16 },
  "is-there-blood-in-the-stool" => { p_yes: 0.05 },
  "has-name-had-convulsions" => { p_yes: 0.02 },
  "does-name-have-difficulty-drinking-or-feeding" => { p_yes: 0.08 },
  "is-name-not-able-to-drink-or-feed-anything" => { p_yes: 0.2 },
  "is-name-vomiting" => { p_yes: 0.12 },
  "is-name-vomiting-everything" => { p_yes: 0.15 },
  "is-name-unusually-sleepy-or-unconscious" => { p_yes: 0.02 },
  "does-child-name-have-any-eye-problem" => { p_yes: 0.05 },
  "has-the-caregiver-taken-name-to-a-dentist-in-the-last-6-months" => { p_yes: 0.2 },
  "does-name-s-caregiver-clean-their-teeth" => { p_yes: 0.85 },
  "what-is-the-muac-color" => { weights: { "green" => 92, "yellow" => 6, "red" => 2 } },
  "check-for-swelling-of-both-feet-by-pressing-both-feet-for-3-seconds-is-there-swe" => { p_yes: 0.01 },
  "does-the-child-have-any-other-problem-or-condition-you-cannot-treat" => { p_yes: 0.03 },
  "is-the-mother-exclusively-breastfeeding-the-child" => { p_yes: 0.6 },
  "is-the-mother-still-breastfeeding-the-child" => { p_yes: 0.7 },
  "did-the-mother-breastfeed-her-child-in-the-last-24-hours" => { p_yes: 0.9 },
  "does-name-have-upto-date-insurance" => { p_yes: 0.55 },
  "have-you-observed-sign-s-of-any-form-of-violence" => { p_yes: 0.01 },
  # Immunization Service
  "is-immunization-up-to-date" => { p_yes: 0.8 },
  "state-the-reason-why-s-immunization-status-is-not-upto-date" => { weights: { "started-late" => 30, "missed-stock-out" => 40, "defaulter-other" => 30 } },
  "does-have-a-next-immunization-appointment-date" => { p_yes: 0.85 },
  "is-child-s-name-deworming-status-upto-date" => { p_yes: 0.7 },
  "deworm-the-child-have-you-dewormed-the-child" => { p_yes: 0.6 },
  "is-participating-in-monthly-growth-monitoring" => { p_yes: 0.75 },
  "is-showing-signs-of-delayed-developmental-milestones" => { p_yes: 0.03 },
  # Pregnancy, PNC, chronic care and follow-up services
  "is-available" => { p_yes: 0.92 },
  "is-still-pregnant" => { p_yes: 0.9 },
  "has-started-anc" => { p_yes: 0.75 },
  "how-many-anc-visits-has-attended" => { range: 0..4 },
  "how-many-anc-visits-has-attended-since-the-last-chp-visit" => { range: 0..2 },
  "is-taking-her-iron-and-folate-suppliments-daily" => { p_yes: 0.7 },
  "does-have-upto-date-insurance" => { p_yes: 0.5 },
  "has-delivered" => { p_yes: 0.97 },
  "what-is-the-condition-of-the-mother" => { weights: { "alive" => 99, "dead" => 1 } },
  "how-many-anc-visits-did-attend-during-this-pregnancy" => { range: 1..8 },
  "how-many-pnc-visits-has-attended" => { range: 0..3 },
  "ask-for-the-following-danger-signs-of-a-new-mother" => { p_answer: 0.08 },
  "is-clinic-up-to-date" => { p_yes: 0.75 },
  "does-have-any-of-these-complications-of-diabetes" => { weights: { "none" => 80, "blurred-vision" => 7, "foot-numbness-or-tingling-sensation" => 8, "slow-healing-or-infected-foot-wound" => 5 } },
  "is-still-on-tb-treatment" => { p_yes: 0.7 },
  "has-completed-the-treatment" => { p_yes: 0.3 },
  "is-clinic-attendance-up-to-date" => { p_yes: 0.8 },
  "have-you-refered-name-to-the-health-facility" => { p_yes: 0.8 },
  "was-pregnant-at-time-of-death" => { p_yes: 0.0 },
  "had-given-birth-within-42-days-before-date-of-death" => { p_yes: 0.0 },
  # Household Registration (WASH)
  "water-source" => { weights: { "piped" => 30, "borehole" => 22, "protected-well" => 18, "surface-water" => 30 } },
  "sanitation-facility" => { weights: { "pit-latrine" => 50, "vip-latrine" => 15, "flush-toilet" => 18, "none" => 17 } },
  "handwashing-facility" => { p_true: 0.45 }
}.freeze

# A fact pins an answer instead of drawing it: a literal FHIR answer hash
# ({"valueString" => ...}), or OptionCode to select the item's own
# answerOption with that code (so system/display come from the form).
OptionCode = Struct.new(:code)

ResponseState = Struct.new(:draw, :answers, :extracted, :display_name, :visit_date, keyword_init: true)

def observation_extract?(item)
  Array(item["extension"]).any? { |extension| extension["url"] == OBSERVATION_EXTRACT_EXTENSION && extension["valueBoolean"] == true }
end

def answer_scalar(answer)
  key = answer.keys.find { |k| k.start_with?("value") }
  value = answer[key]
  value.is_a?(Hash) ? value["code"] : value
end

def enable_when_met?(condition, answers)
  answer = answers[condition["question"]]
  operator = condition["operator"]
  return answer.nil? != condition["answerBoolean"] if operator == "exists"
  return operator == "!=" if answer.nil?

  expected_key = condition.keys.find { |key| key.start_with?("answer") }
  expected = condition[expected_key]
  expected = expected["code"] if expected.is_a?(Hash)
  actual = answer_scalar(answer)

  case operator
  when "=" then actual == expected
  when "!=" then actual != expected
  when ">", "<", ">=", "<="
    actual.is_a?(Numeric) && expected.is_a?(Numeric) ? actual.public_send(operator, expected) : false
  else false
  end
end

def item_enabled?(item, answers)
  conditions = Array(item["enableWhen"])
  return true if conditions.empty?

  results = conditions.map { |condition| enable_when_met?(condition, answers) }
  item["enableBehavior"] == "any" ? results.any? : results.all?
end

def render_text(text, state) = text.gsub("{{name}}", state.display_name)

def choose_option(options, profile, draw)
  if profile && profile[:weights]
    pairs = options.filter_map { |option| weight = profile[:weights][option["code"]]; [option, weight] if weight&.positive? }
    return draw.weighted(pairs) unless pairs.empty?
  end

  codes = options.map { |option| option["code"] }
  if codes.sort == %w[no yes]
    yes = draw.chance?(profile&.fetch(:p_yes, nil) || DEFAULT_P_YES)
    return options.find { |option| option["code"] == (yes ? "yes" : "no") }
  end

  none = options.find { |option| option["code"] == "none" }
  return none if none && draw.chance?(NONE_OPTION_PROBABILITY)

  others = options.reject { |option| option.equal?(none) }
  draw.pick(others.empty? ? options : others)
end

def drawn_answer(item, state)
  profile = ANSWER_PROFILES[item["linkId"]]
  draw = state.draw
  return nil if profile&.key?(:p_answer) && !draw.chance?(profile[:p_answer])

  case item["type"]
  when "choice", "open-choice"
    options = Array(item["answerOption"]).filter_map { |option| option["valueCoding"] }
    return nil if options.empty?

    { "valueCoding" => choose_option(options, profile, draw) }
  when "boolean"
    { "valueBoolean" => draw.chance?(profile&.fetch(:p_true, nil) || 0.5) }
  when "integer"
    range = profile&.fetch(:range, nil) || (0..10)
    { "valueInteger" => draw.int(range.min, range.max) }
  when "decimal"
    range = profile&.fetch(:range, nil) || (0.0..10.0)
    { "valueDecimal" => (range.min + (draw.float * (range.max - range.min))).round(1) }
  when "date"
    offset = item["linkId"].match?(/next|appointment|edd|follow-up/) ? draw.int(7, 60) : -draw.int(0, 60)
    { "valueDate" => (state.visit_date + offset).iso8601 }
  when "string", "text"
    item["required"] ? { "valueString" => "Recorded during CHP home visit" } : nil
  end
end

def resolve_answer(item, state, facts)
  link_id = item["linkId"]
  return drawn_answer(item, state) unless facts.key?(link_id)

  fact = facts[link_id]
  return fact unless fact.is_a?(OptionCode)

  option = Array(item["answerOption"]).filter_map { |o| o["valueCoding"] }.find { |coding| coding["code"] == fact.code }
  option ? { "valueCoding" => option } : nil
end

def response_items(items, state, facts)
  Array(items).flat_map do |item|
    next [] unless item_enabled?(item, state.answers)

    node = { "linkId" => item["linkId"] }
    node["text"] = render_text(item["text"], state) if item["text"]

    case item["type"]
    when "group"
      repeats = facts[item["linkId"]]
      fact_sets = repeats.is_a?(Array) ? repeats : [{}]
      fact_sets.filter_map do |fact_set|
        children = response_items(item["item"], state, facts.merge(fact_set))
        children.empty? ? nil : node.merge("item" => children)
      end
    when "display"
      [node]
    else
      answer = resolve_answer(item, state, facts)
      if answer
        state.answers[item["linkId"]] = answer
        state.extracted << [item, answer] if observation_extract?(item)
        nested = response_items(item["item"], state, facts)
        node["answer"] = [nested.empty? ? answer : answer.merge("item" => nested)]
      end
      [node]
    end
  end
end

# --- Visits ---------------------------------------------------------------------

Visit = Struct.new(:slug, :questionnaire, :plan_definition_id, :person, :start_time, :end_time, :encounter_id,
                   :response_id, :answers, :observations, :resources, keyword_init: true) do
  # Extracted Observations by their code, each as [observation, scalar value, item].
  def observation_for(code) = observations.find { |entry| entry.first.dig("code", "coding", 0, "code") == code }
  def value_for(code) = observation_for(code)&.at(1)
  def date = start_time.to_date
end

GenerationContext = Struct.new(:content, :seed, :catchment, :chv, :include_specimen, keyword_init: true)

def observation_value(item, answer)
  if answer["valueCoding"]
    { "valueCodeableConcept" => { "coding" => [answer["valueCoding"]] } }
  elsif answer.key?("valueDecimal")
    quantity = { "value" => answer["valueDecimal"] }
    quantity.merge!("unit" => "Cel", "system" => "http://unitsofmeasure.org", "code" => "Cel") if item.dig("code", 0, "code") == "temperature-celsius"
    { "valueQuantity" => quantity }
  elsif answer.key?("valueDate")
    { "valueDateTime" => answer["valueDate"] }
  else
    key = answer.keys.find { |k| k.start_with?("value") }
    { key => answer[key] }
  end
end

# Walks one form for one person and returns the Encounter, the
# QuestionnaireResponse and its extracted Observations -- the same trio the
# app writes for every service visit. subject/encounter wiring mirrors the
# dev server: household forms target the Group and have no Encounter.
def run_visit(ctx, slug:, questionnaire_id:, plan_definition_id:, person:, subject:, facts: {}, day_window: 0..89, with_encounter: true)
  questionnaire = ctx.content.questionnaire(questionnaire_id)
  draw = Draw.new(ctx.seed, person.index, slug)
  date = REFERENCE_DATE - draw.int(day_window.min, day_window.max)
  start_time = day_time(date, draw.int(0, 600))
  end_time = start_time + (draw.int(3, 25) * 60)
  state = ResponseState.new(draw: draw, answers: {}, extracted: [], display_name: person.given.first, visit_date: date)
  items = response_items(questionnaire["item"], state, facts)

  encounter_id = with_encounter ? visit_resource_id("enc", slug, person.index) : nil
  response_id = visit_resource_id("qr", slug, person.index)
  tag = sync_tag(ctx.catchment.unit_id)
  resources = []

  if with_encounter
    resources << {
      "resourceType" => "Encounter",
      "id" => encounter_id,
      "meta" => tag,
      "extension" => [plan_definition_extension(plan_definition_id)],
      "status" => "finished",
      "class" => { "system" => ACT_CODE_SYSTEM, "code" => "FLD", "display" => "Field" },
      "subject" => subject,
      "period" => { "start" => timestamp(start_time), "end" => timestamp(end_time) }
    }
  end

  response = {
    "resourceType" => "QuestionnaireResponse",
    "id" => response_id,
    "meta" => tag,
    "extension" => [
      { "url" => LAST_LAUNCHED_EXTENSION, "valueDateTime" => timestamp(start_time) },
      plan_definition_extension(plan_definition_id)
    ],
    "questionnaire" => questionnaire["url"],
    "status" => "completed",
    "subject" => subject
  }
  response["encounter"] = reference("Encounter", encounter_id) if encounter_id
  response["authored"] = timestamp(end_time)
  response["item"] = items
  resources << response

  observations = state.extracted.each_with_index.map do |(item, answer), position|
    observation = {
      "resourceType" => "Observation",
      "id" => visit_resource_id("obs", slug, person.index, position),
      "meta" => tag,
      "status" => "final",
      "code" => { "coding" => [item.dig("code", 0).slice("system", "code", "display")] },
      "subject" => subject
    }
    observation["encounter"] = reference("Encounter", encounter_id) if encounter_id
    observation["effectiveDateTime"] = timestamp(end_time)
    observation.merge!(observation_value(item, answer))
    observation["derivedFrom"] = [reference("QuestionnaireResponse", response_id)]
    resources << observation
    [observation, answer_scalar(answer), item]
  end

  Visit.new(slug: slug, questionnaire: questionnaire, plan_definition_id: plan_definition_id, person: person,
            start_time: start_time, end_time: end_time, encounter_id: encounter_id, response_id: response_id,
            answers: state.answers, observations: observations, resources: resources)
end

def detected_issue(ctx, visit, rule_id, evidence, position)
  observation, value, item = evidence
  display_value = observation.dig("valueCodeableConcept", "coding", 0, "display") || value.to_s
  question = item["text"].to_s.gsub("{{name}}", visit.person.given.first)
  {
    "resourceType" => "DetectedIssue",
    "id" => visit_resource_id("di", visit.slug, visit.person.index, position),
    "meta" => sync_tag(ctx.catchment.unit_id),
    "extension" => [plan_definition_extension(rule_id)],
    "status" => "preliminary",
    "code" => { "coding" => [{ "system" => DECISION_SUPPORT_RULE_SYSTEM, "code" => rule_id, "display" => ctx.content.plan_title(rule_id) }] },
    "severity" => "high",
    "patient" => reference("Patient", visit.person.id),
    "identifiedDateTime" => timestamp(visit.end_time),
    "author" => reference("PractitionerRole", ctx.chv[:role_id]),
    "implicated" => [reference("QuestionnaireResponse", visit.response_id)],
    "evidence" => [{ "detail" => [reference("Observation", observation["id"])] }],
    "detail" => "#{question} of #{display_value} recorded on #{visit.date.strftime("%d-%m-%Y")} while completing #{visit.questionnaire["title"]}."
  }
end

def follow_up_task(ctx, visit, slug:, plan_definition_id:, activity:, code:, display:, priority:, status:, due_in_days:, reason: nil)
  task = {
    "resourceType" => "Task",
    "id" => visit_resource_id("task", slug, visit.person.index),
    "meta" => sync_tag(ctx.catchment.unit_id),
    "extension" => [plan_definition_extension(plan_definition_id)],
    "instantiatesCanonical" => "ActivityDefinition/#{activity}",
    "status" => status,
    "intent" => "order",
    "priority" => priority,
    "code" => { "coding" => [{ "code" => code, "display" => display }] },
    "for" => reference("Patient", visit.person.id),
    "authoredOn" => timestamp(visit.end_time),
    "owner" => reference("PractitionerRole", ctx.chv[:role_id], ctx.chv[:name]),
    "restriction" => { "period" => { "end" => (visit.date + due_in_days).iso8601 } }
  }
  task["reasonReference"] = reference("DetectedIssue", reason["id"]) if reason
  task
end

CONDITION_CODES = {
  "malaria" => { "code" => "61462000", "display" => "Malaria" },
  "pregnancy" => { "code" => "77386006", "display" => "Pregnancy" },
  "diabetes" => { "code" => "44054006", "display" => "Diabetes mellitus type 2" },
  "tb" => { "code" => "56717001", "display" => "Tuberculosis" }
}.freeze

def condition_resource(ctx, visit, key, verification)
  {
    "resourceType" => "Condition",
    "id" => visit_resource_id("cond", visit.slug, visit.person.index),
    "meta" => sync_tag(ctx.catchment.unit_id),
    "clinicalStatus" => { "coding" => [{ "system" => "http://terminology.hl7.org/CodeSystem/condition-clinical", "code" => "active" }] },
    "verificationStatus" => { "coding" => [{ "system" => "http://terminology.hl7.org/CodeSystem/condition-ver-status", "code" => verification }] },
    "category" => [{ "coding" => [{ "system" => "http://terminology.hl7.org/CodeSystem/condition-category", "code" => "problem-list-item" }] }],
    "code" => { "coding" => [{ "system" => SNOMED_SYSTEM }.merge(CONDITION_CODES.fetch(key))] },
    "subject" => reference("Patient", visit.person.id),
    "encounter" => reference("Encounter", visit.encounter_id),
    "recordedDate" => timestamp(visit.end_time),
    "recorder" => reference("PractitionerRole", ctx.chv[:role_id]),
    "evidence" => [{ "detail" => [reference("QuestionnaireResponse", visit.response_id)] }]
  }
end

def yes?(value) = value == "yes"

def fast_breathing_threshold(person)
  return 60 if person.age_months < 2
  return 50 if person.age_months < 12

  40
end

# Decision rules, keyed to the snapshot's decision-support PlanDefinitions
# (their ids double as the DetectedIssue code, as on the dev server).
UNDER_FIVE_ALERT_RULES = [
  ["under-5-fast-breathing-alert", "breaths-per-minute", ->(value, person, _) { value >= fast_breathing_threshold(person) }],
  ["under-5-high-temperature-alert", "temperature-celsius", ->(value, _, _) { value >= 38.0 }],
  ["under-5-low-temperature-alert", "temperature-celsius", ->(value, _, _) { value <= 35.4 }],
  ["under-5-diarrhoea-over-14-days-alert", "diarrhoea-duration-days", ->(value, _, _) { value > 14 }],
  ["under-5-blood-in-stool-alert", "blood-in-stool", ->(value, _, _) { yes?(value) }],
  ["under-5-chest-in-drawing-alert", "chest-in-drawing", ->(value, _, _) { yes?(value) }],
  ["under-5-convulsions-alert", "convulsions", ->(value, _, _) { yes?(value) }],
  ["under-5-unable-to-drink-or-feed-alert", "unable-to-drink-or-feed", ->(value, _, _) { yes?(value) }],
  ["under-5-vomiting-everything-alert", "vomiting-everything", ->(value, _, _) { yes?(value) }],
  ["under-5-unusually-sleepy-or-unconscious-alert", "unusually-sleepy-or-unconscious", ->(value, _, _) { yes?(value) }],
  ["under-5-muac-red-alert", "muac-color", ->(value, _, _) { value == "red" }],
  ["under-5-muac-yellow-alert", "muac-color", ->(value, _, _) { value == "yellow" }],
  ["under-5-swelling-of-both-feet-alert", "swelling-of-both-feet", ->(value, _, _) { yes?(value) }],
  ["under-5-malaria-negative-with-fever-alert", "malaria-rdt-result", ->(value, _, visit) { value == "negative" && yes?(visit.value_for("fever")) }]
].freeze
CORE_DANGER_SIGN_CODES = %w[chest-in-drawing convulsions unable-to-drink-or-feed vomiting-everything unusually-sleepy-or-unconscious].freeze
ANY_CORE_DANGER_SIGN_RULE = "under-5-any-core-danger-sign-refer-immediately-alert"

def alerts_for(ctx, visit, rules)
  issues = []
  rules.each do |rule_id, code, predicate|
    evidence = visit.observation_for(code)
    next unless evidence && predicate.call(evidence[1], visit.person, visit)

    issues << detected_issue(ctx, visit, rule_id, evidence, issues.length)
  end
  issues
end

# A referral raised during a visit becomes an urgent Task for the CHV; about
# half are already closed out by a Referral Follow Up visit.
def referral_resources(ctx, visit, issues)
  return [] if issues.empty?

  draw = Draw.new(ctx.seed, visit.person.index, "#{visit.slug}-referral")
  followed_up = draw.chance?(0.5)
  resources = [
    follow_up_task(ctx, visit, slug: "ref#{visit.slug}", plan_definition_id: "plandefinition-referral-follow-up-alert",
                   activity: "act-refer-patient", code: "follow-up-on-referral", display: "Follow up on referral",
                   priority: "urgent", status: followed_up ? "completed" : "requested", due_in_days: 3, reason: issues.first)
  ]
  if followed_up
    resources.concat(run_visit(ctx, slug: "fu#{visit.slug}", questionnaire_id: "referral-follow-up-questionnaire",
                               plan_definition_id: "plandefinition-referral-follow-up", person: visit.person,
                               subject: reference("Patient", visit.person.id), day_window: 0..0).resources)
  end
  resources
end

def under_five_visit(ctx, person)
  breaths_draw = Draw.new(ctx.seed, person.index, "u5-breaths")
  threshold = fast_breathing_threshold(person)
  facts = { "how-many-breaths-per-minute" => { "valueInteger" => breaths_draw.int(threshold - 18, threshold + 2) } }
  visit = run_visit(ctx, slug: "u5", questionnaire_id: "under-5-assessment-service-questionnaire",
                    plan_definition_id: "plandefinition-under-5-workflow", person: person,
                    subject: reference("Patient", person.id), facts: facts)
  resources = visit.resources.dup
  issues = alerts_for(ctx, visit, UNDER_FIVE_ALERT_RULES)
  core = CORE_DANGER_SIGN_CODES.filter_map { |code| visit.observation_for(code) if yes?(visit.value_for(code)) }.first
  issues << detected_issue(ctx, visit, ANY_CORE_DANGER_SIGN_RULE, core, issues.length) if core
  resources.concat(issues)

  if visit.value_for("malaria-rdt-result") == "positive"
    resources << condition_resource(ctx, visit, "malaria", "provisional")
  end
  if ctx.include_specimen && visit.observation_for("malaria-rdt-result")
    resources << {
      "resourceType" => "Specimen",
      "id" => format("echis-spec%08d", person.index),
      "meta" => sync_tag(ctx.catchment.unit_id),
      "status" => "available",
      "type" => { "coding" => [{ "system" => SNOMED_SYSTEM, "code" => "119297000", "display" => "Blood specimen" }] },
      "subject" => reference("Patient", person.id),
      "collection" => { "collectedDateTime" => timestamp(visit.end_time) }
    }
  end
  resources.concat(referral_resources(ctx, visit, issues))
end

IMMUNIZATION_ALERT_RULES = [
  ["immunization-delayed-developmental-milestone-refer-alert", "delayed-milestone", ->(_, _, _) { true }],
  ["immunization-defaulter-other-reasons-refer-alert", "not-up-to-date-reason", ->(value, _, _) { value == "defaulter-other" }]
].freeze

def immunization_visit(ctx, person)
  visit = run_visit(ctx, slug: "imm", questionnaire_id: "immunization-service-questionnaire",
                    plan_definition_id: "plandefinition-immunization-service", person: person,
                    subject: reference("Patient", person.id))
  resources = visit.resources.dup
  issues = alerts_for(ctx, visit, IMMUNIZATION_ALERT_RULES)
  resources.concat(issues)
  resources.concat(referral_resources(ctx, visit, issues))

  if visit.observation_for("not-up-to-date-reason") && Draw.new(ctx.seed, person.index, "defaulter").chance?(0.5)
    tracing = run_visit(ctx, slug: "dft", questionnaire_id: "defaulter-follow-up-questionnaire",
                        plan_definition_id: "plandefinition-defaulter-follow-up", person: person,
                        subject: reference("Patient", person.id), day_window: 0..0)
    resources.concat(tracing.resources)
  end
  resources
end

def pregnancy_visits(ctx, person)
  screening = run_visit(ctx, slug: "psr", questionnaire_id: "pregnancy-screening-registration-questionnaire",
                        plan_definition_id: "plandefinition-pregnancy-screening-registration", person: person,
                        subject: reference("Patient", person.id), day_window: 60..200)
  resources = screening.resources.dup
  resources << condition_resource(ctx, screening, "pregnancy", "confirmed")

  draw = Draw.new(ctx.seed, person.index, "anc")
  if draw.chance?(0.7)
    home = run_visit(ctx, slug: "anc", questionnaire_id: "pregnancy-home-service-questionnaire",
                     plan_definition_id: "plandefinition-pregnancy-home-service", person: person,
                     subject: reference("Patient", person.id), day_window: 0..59)
    resources.concat(home.resources)
  end
  resources << follow_up_task(ctx, screening, slug: "anc", plan_definition_id: "plandefinition-pregnancy-home-service",
                              activity: "act-general-assessment", code: "pregnancy-home-service", display: "Pregnancy Home Service",
                              priority: "routine", status: "requested", due_in_days: 30)
end

def postnatal_visit(ctx, mother)
  visit = run_visit(ctx, slug: "pnc", questionnaire_id: "mother-newborn-pnc-home-service-questionnaire",
                    plan_definition_id: "plandefinition-mother-newborn-pnc-home-service", person: mother,
                    subject: reference("Patient", mother.id), day_window: 0..30)
  issues = alerts_for(ctx, visit, [["plandefinition-pnc-mother-danger-sign-alert", "pnc-mother-danger-sign", ->(_, _, _) { true }]])
  visit.resources + issues + referral_resources(ctx, visit, issues)
end

def chronic_visit(ctx, person, slug, questionnaire_id, plan_definition_id, condition_key)
  visit = run_visit(ctx, slug: slug, questionnaire_id: questionnaire_id, plan_definition_id: plan_definition_id,
                    person: person, subject: reference("Patient", person.id))
  visit.resources + [condition_resource(ctx, visit, condition_key, "confirmed")]
end

# Visit mix per individual. Under-5 care dominates (every under-5 child has
# an assessment; most also an immunization visit), pregnancy and postnatal
# care are next, and chronic care and death reports are rare -- the mix
# agreed for the dev-server-aligned dataset. Returns [resources, deceased_at].
PREGNANCY_RATE = 0.08
POSTNATAL_RATE = 0.6
DIABETES_RATE = 0.05
TB_RATE = 0.006
DEATH_RATE = 0.015

def person_visits(ctx, person, roster)
  draw = Draw.new(ctx.seed, person.index, "visit-mix")
  resources = []
  deceased_at = nil
  under_five = person.age_months < 60

  if under_five
    resources.concat(under_five_visit(ctx, person))
    resources.concat(immunization_visit(ctx, person)) if draw.chance?(person.age_months < 24 ? 0.7 : 0.3)
  end

  woman_of_reproductive_age = person.gender == "female" && person.age_years.between?(15, 49) && %w[head spouse].include?(person.role)
  if woman_of_reproductive_age
    resources.concat(pregnancy_visits(ctx, person)) if draw.chance?(PREGNANCY_RATE)
    has_infant = roster.any? { |member| member.role == "child" && member.age_days < 180 }
    resources.concat(postnatal_visit(ctx, person)) if has_infant && draw.chance?(POSTNATAL_RATE)
  end

  if person.age_years >= 35 && draw.chance?(DIABETES_RATE)
    resources.concat(chronic_visit(ctx, person, "dm", "diabetes-service-questionnaire", "plandefinition-diabetes-service", "diabetes"))
  end
  if person.age_years >= 15 && draw.chance?(TB_RATE)
    resources.concat(chronic_visit(ctx, person, "tb", "tb-service-questionnaire", "plandefinition-tb-service", "tb"))
  end
  if person.age_years >= 60 && draw.chance?(DEATH_RATE)
    report = run_visit(ctx, slug: "death", questionnaire_id: "death-report-questionnaire",
                       plan_definition_id: "plandefinition-death-report", person: person,
                       subject: reference("Patient", person.id), day_window: 0..0)
    resources.concat(report.resources)
    deceased_at = report.start_time - (2 * 86_400)
  end

  [resources, deceased_at]
end

WASH_OBSERVATIONS = [
  ["water-source", "Main drinking water source"],
  ["sanitation-facility", "Household sanitation facility"],
  ["handwashing-facility", "Handwashing facility available"]
].freeze

def household_registration(ctx, household_index, roster, group_reference)
  head = roster.first
  catchment = ctx.catchment
  national_id_draw = Draw.new(ctx.seed, head.index, "national-id")
  facts = {
    "household-id" => { "valueString" => household_id(household_index) },
    "household-name" => { "valueString" => "#{head.family} Household" },
    "county" => { "valueString" => catchment.county["name"] },
    "sub-county" => { "valueString" => catchment.sub_county_name },
    "ward" => { "valueString" => catchment.ward_name },
    "village" => { "valueString" => village_name(household_index) },
    "head-given-name" => { "valueString" => head.given.join(" ") },
    "head-family-name" => { "valueString" => head.family },
    "head-national-id" => { "valueString" => format("%08d", national_id_draw.int(10_000_000, 39_999_999)) },
    "head-gender" => OptionCode.new(head.gender),
    "head-birth-date" => { "valueDate" => head.birth_date.iso8601 },
    "head-phone" => head.phone ? { "valueString" => head.phone } : nil,
    "household-members" => roster.drop(1).map do |member|
      {
        "member-given-name" => { "valueString" => member.given.join(" ") },
        "member-family-name" => { "valueString" => member.family },
        "member-gender" => OptionCode.new(member.gender),
        "member-birth-date" => { "valueDate" => member.birth_date.iso8601 },
        "member-relationship-to-head" => OptionCode.new(member.relationship)
      }
    end
  }
  registration = run_visit(ctx, slug: "hh", questionnaire_id: "household-registration",
                           plan_definition_id: "plandefinition-household-registration", person: head,
                           subject: group_reference, facts: facts, day_window: 90..540, with_encounter: false)
  response = registration.resources.first
  response["extension"].pop # the dev server's household registrations carry no PlanDefinition link

  observations = WASH_OBSERVATIONS.each_with_index.filter_map do |(link_id, display), position|
    answer = registration.answers[link_id]
    next unless answer

    {
      "resourceType" => "Observation",
      "id" => format("echis-obs-hh%08d-%d", household_index, position),
      "meta" => sync_tag(catchment.unit_id),
      "status" => "final",
      "code" => { "coding" => [{ "system" => HOUSEHOLD_WASH_SYSTEM, "code" => link_id, "display" => display }] },
      "subject" => group_reference,
      "effectiveDateTime" => response["authored"]
    }.merge(observation_value({}, answer)).merge("derivedFrom" => [reference("QuestionnaireResponse", response["id"])])
  end

  [registration, [response] + observations]
end

def resources_for_household(household_index, individuals_per_household, content, seed, include_specimen, catchment_cache)
  chw_index = chw_index_for(household_index)
  catchment = catchment_for(unit_index_for(chw_index), content, seed, catchment_cache)
  chv = { role_id: chw_practitioner_role_id(chw_index), name: chv_name(chw_index, seed) }
  ctx = GenerationContext.new(content: content, seed: seed, catchment: catchment, chv: chv, include_specimen: include_specimen)
  roster = household_roster(household_index, individuals_per_household, seed)
  head = roster.first

  group_reference = reference("Group", household_id(household_index))
  registration, registration_resources = household_registration(ctx, household_index, roster, group_reference)
  registered_on = registration.date

  people = []
  visits = []
  roster.each do |person|
    person_resources, deceased_at = person_visits(ctx, person, roster)
    people << patient_resource(person, head, catchment, household_index, chv, deceased_at)
    people << related_person_resource(person, head, catchment) if person.relationship
    visits.concat(person_resources)
  end

  [group_resource(household_index, roster, catchment, chv, registered_on)] + people + registration_resources + visits
end

PROGRESS_BAR_WIDTH = 24

def progress_bar(percent)
  filled = ((PROGRESS_BAR_WIDTH * percent) / 100.0).round.clamp(0, PROGRESS_BAR_WIDTH)
  ("#" * filled) + ("." * (PROGRESS_BAR_WIDTH - filled))
end

# Renders a "count and percentage" progress update for the current batch.
# Throttled to at most one line per whole percentage point crossed (plus
# always on the final batch), so a run of thousands of batches doesn't
# flood the log regardless of --batch-size. On a real terminal, updates
# overwrite the same line via \r for a live-looking progress bar; anywhere
# else (piped to a file, captured by `scripts/lab`, streamed through the
# Lab Control UI's SSE log -- none of which interpret \r as "overwrite
# the previous line") each update is emitted as its own line instead.
def report_progress(verb, done, total, shard_index, shard_count, last_reported_percent)
  percent = total.positive? ? ((done * 100.0) / total) : 100.0
  floor_percent = percent.floor
  finished = done >= total
  return last_reported_percent unless finished || floor_percent > last_reported_percent

  line = format(
    "%s households %d/%d [%s] %3d%% (shard %d/%d)",
    verb, done, total, progress_bar(percent), floor_percent, shard_index, shard_count
  )

  if $stdout.tty?
    print "\r#{line}"
    print "\n" if finished
    $stdout.flush
  else
    puts line
  end

  floor_percent
end

def require_option(options, key)
  value = options[key]
  return value unless value.nil? || value.to_s.empty?

  raise SeedError, "missing required option --#{key.to_s.tr("_", "-")}"
end

begin
  households = require_option(options, :households)
  individuals_per_household = require_option(options, :individuals_per_household)
  seed = require_option(options, :seed)
  run_id = require_option(options, :run_id)
  metadata_path = require_option(options, :metadata)
  batch_size = require_option(options, :batch_size)
  timeout = require_option(options, :timeout)
  max_retries = require_option(options, :max_retries)
  shard_index = require_option(options, :shard_index)
  shard_count = require_option(options, :shard_count)
  metadata_only = options[:metadata_only]

  raise SeedError, "--households must be greater than zero" unless households.positive?
  raise SeedError, "--individuals-per-household must be greater than zero" unless individuals_per_household.positive?
  raise SeedError, "--seed must be non-negative" if seed.negative?
  raise SeedError, "--batch-size must be greater than zero" unless batch_size.positive?
  raise SeedError, "--timeout must be greater than zero" unless timeout.positive?
  raise SeedError, "--max-retries must be non-negative" if max_retries.negative?
  raise SeedError, "--shard-count must be greater than zero" unless shard_count.positive?
  raise SeedError, "--shard-index must be non-negative and less than --shard-count" unless shard_index >= 0 && shard_index < shard_count

  fhir_base_url = options[:fhir_base_url].to_s.sub(%r{/+\z}, "")
  uri = nil
  unless metadata_only
    raise SeedError, "missing required option --fhir-base-url" if fhir_base_url.empty?

    uri = URI(fhir_base_url)
    raise SeedError, "FHIR base URL must be http or https: #{fhir_base_url}" unless %w[http https].include?(uri.scheme)
  end

  content = load_content(options[:content])

  # Contiguous household index range for this shard, per
  # specs/008-echis-workload-benchmark/contracts/echis-seed-cli.md's sharding
  # contract. Resource IDs are derived only from global household/individual
  # indices, never from shard_index itself, so re-running a single shard
  # reproduces byte-identical output and shards never collide.
  start_index = (households * shard_index) / shard_count
  end_index = (households * (shard_index + 1)) / shard_count

  started_at = Time.now.utc
  http_status_counts = Hash.new(0)
  fhir_response_status_counts = Hash.new(0)
  errors = []
  imported_entry_count = 0
  transaction_bundle_count = 0
  resource_counts = Hash.new(0)
  catchment_cache = {}
  emitted_unit_indices = Set.new
  emitted_chw_indices = Set.new
  organization_emitted = false
  last_reported_percent = -1

  # Counts one submitted bundle's response into the metadata tallies.
  # Returns true when the bundle was accepted in full.
  record_response = lambda do |response, entries, batch, count_imports|
    http_status_counts[response.code] += 1
    unless response.code.to_i >= 200 && response.code.to_i < 300
      errors << { "batch" => batch, "http_status" => response.code, "message" => response.body.to_s[0, 500] }
      next false
    end

    entries_response = response_entries(response.body)
    if entries_response.length < entries.length
      errors << {
        "batch" => batch,
        "http_status" => response.code,
        "message" => "partial transaction response: expected at least #{entries.length} entries, got #{entries_response.length}"
      }
    end
    entries_response.each do |entry|
      status = entry.dig("response", "status").to_s
      fhir_response_status_counts[status] += 1 if count_imports
      imported_entry_count += 1 if count_imports && status_success?(status)
    end
    entries_response.length >= entries.length
  end

  # Reference content goes in first, from every shard: household data
  # references the county Locations, and shards start in parallel. It is
  # counted (and reported as imported) by shard 0 only, so a merged
  # multi-shard metadata file counts it once.
  count_content = shard_index.zero?
  content.resources.each { |resource| resource_counts[resource["resourceType"]] += 1 } if count_content
  content_entries = content.resources.map { |resource| put_entry(resource) }
  if metadata_only
    imported_entry_count += content_entries.length if count_content
  else
    begin
      response = post_bundle_with_retries(uri, { "resourceType" => "Bundle", "type" => "transaction", "entry" => content_entries }, timeout, max_retries)
      unless record_response.call(response, content_entries, "content", count_content)
        raise SeedError, "reference content load failed (HTTP #{response.code}), and household data depends on it: #{errors.last&.fetch("message", nil)}"
      end
    rescue SeedError
      raise
    rescue StandardError => e
      errors << { "batch" => "content", "message" => "#{e.class}: #{e.message}" }
      raise SeedError, "reference content load failed: #{e.class}: #{e.message}"
    end
  end

  (start_index...end_index).each_slice(batch_size) do |household_indices|
    transaction_bundle_count += 1
    resources = []

    household_indices.each do |household_index|
      unless organization_emitted
        resources << organization_resource
        organization_emitted = true
      end

      # emitted_*_indices are per-invocation (per-shard), not global: a
      # catchment straddling a shard boundary is PUT once by each shard that
      # touches it. That is idempotent-safe (identical content) and avoids
      # cross-shard coordination; it can inflate the *reported* counts for
      # Location/Practitioner/PractitionerRole/CareTeam/Organization when
      # shard metadata are summed, but never the resources on the server, and
      # never the household-owned types, which exactly one shard generates.
      chw_index = chw_index_for(household_index)
      unit_index = unit_index_for(chw_index)
      catchment = catchment_for(unit_index, content, seed, catchment_cache)
      unless emitted_unit_indices.include?(unit_index)
        resources.concat(catchment_resources(catchment))
        emitted_unit_indices << unit_index
      end
      unless emitted_chw_indices.include?(chw_index)
        resources.concat(chw_resources(chw_index, catchment, seed))
        emitted_chw_indices << chw_index
      end

      resources.concat(resources_for_household(household_index, individuals_per_household, content, seed, options[:include_specimen], catchment_cache))
    end

    resources.each { |resource| resource_counts[resource["resourceType"]] += 1 }
    entries = resources.map { |resource| put_entry(resource) }
    progress_done = household_indices.last + 1 - start_index
    progress_total = end_index - start_index

    if metadata_only
      imported_entry_count += entries.length
      last_reported_percent = report_progress("Would import", progress_done, progress_total, shard_index, shard_count, last_reported_percent)
      next
    end

    bundle = { "resourceType" => "Bundle", "type" => "transaction", "entry" => entries }
    response = post_bundle_with_retries(uri, bundle, timeout, max_retries)
    record_response.call(response, entries, transaction_bundle_count, true)
    last_reported_percent = report_progress("Imported", progress_done, progress_total, shard_index, shard_count, last_reported_percent)
  rescue StandardError => e
    errors << { "batch" => transaction_bundle_count, "message" => "#{e.class}: #{e.message}" }
  end

  completed_at = Time.now.utc
  generated_entry_count = resource_counts.values.sum
  metadata = {
    "run_id" => run_id,
    "echis" => {
      "households" => households,
      "individuals_per_household" => individuals_per_household,
      "patients" => total_individuals(households, individuals_per_household),
      "seed" => seed,
      "generator" => "echis_seed",
      "data_model" => "echis-dev-aligned",
      "content_source" => File.basename(options[:content]),
      "content_resource_count" => content.resources.length,
      "shard_index" => shard_index,
      "shard_count" => shard_count,
      "start_index" => start_index,
      "end_index" => end_index,
      "transaction_bundle_count" => transaction_bundle_count,
      "generated_entry_count" => generated_entry_count,
      "resource_counts" => resource_counts.sort.to_h
    },
    "import" => {
      "mode" => metadata_only ? "metadata-only" : "transaction-load",
      "fhir_base_url" => metadata_only ? nil : fhir_base_url,
      "started_at_utc" => started_at.iso8601,
      "completed_at_utc" => completed_at.iso8601,
      "duration_seconds" => (completed_at - started_at).round(3),
      "http_status_counts" => http_status_counts.sort.to_h,
      "fhir_response_status_counts" => fhir_response_status_counts.sort.to_h,
      "submitted_entry_count" => generated_entry_count,
      "imported_entry_count" => imported_entry_count,
      "error_count" => errors.length,
      "errors" => errors
    },
    "created_at_utc" => started_at.iso8601,
    "completed_at_utc" => completed_at.iso8601
  }

  FileUtils.mkdir_p(File.dirname(metadata_path))
  File.write(metadata_path, "#{JSON.pretty_generate(metadata)}\n")

  unless errors.empty?
    warn "eCHIS seed failed with #{errors.length} error(s); see #{metadata_path}"
    exit 1
  end

  puts "Wrote eCHIS dataset metadata to #{metadata_path}"
  puts "#{metadata_only ? "Would import" : "Imported"} #{imported_entry_count} resource entries#{metadata_only ? "" : " into #{fhir_base_url}"}."
rescue SeedError => e
  warn "scripts/echis_seed.rb: #{e.message}"
  exit 1
end
